name: Security Audit

on:
  schedule:
    - cron: "0 3 * * 1" # Lunes 03:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (production only)
        run: npm install --omit=dev

      - name: Run npm audit (high severity)
        id: audit
        run: |
          set +e
          npm audit --audit-level=high --json > npm-audit.json
          EXIT_CODE=$?
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
          exit 0

      - name: Upload audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: npm-audit.json

      - name: Fail if vulnerabilities found
        if: steps.audit.outputs.exit_code != '0'
        run: |
          echo "npm audit detected vulnerabilities with exit code ${AUDIT_EXIT}"
          exit 1
        env:
          AUDIT_EXIT: ${{ steps.audit.outputs.exit_code }}
